name: build-push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Show GITHUB_REF
        run: echo "${GITHUB_REF}"
      - name Show short
        run: echo "${GITHUB_REF##*/}"
      - name: Set tag
        run: short=${GITHUB_REF##*/} echo "tag=${short/master/latest}" >> $GITHUB_ENV
      - name: Show GITHUB_ENV file
        run: cat "${GITHUB_ENV}"
      - name: Show GITHUB_ENV
        run: echo "${GITHUB_ENV}"
      - name: Show tag
        run: echo "${tag}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: robertdebock/github-action-molecule:${{ env.tag }}
